// Les écussons des clubs du vivier — FICHIER GÉNÉRÉ.
// `python3 tools/telecharger-logos.py` le réécrit ; ne pas le
// corriger à la main, la table des sources est dans l'outil.
//
// Le nom EXACT du club au vivier mène à son fichier. Un club absent
// de cette table n'a pas d'écusson, et l'interface le sait avant
// de dessiner — pas d'image cassée, pas de requête pour rien.

export const LOGOS_CLUBS = {
  "AC Milan": "ac-milan.png",
  "AJ Auxerre": "aj-auxerre.png",
  "AS Cannes": "as-cannes.png",
  "AS Monaco": "as-monaco.png",
  "AS Nancy-Lorraine": "as-nancy-lorraine.png",
  "AS Roma": "as-roma.png",
  "AS Saint-Étienne": "as-saint-etienne.png",
  "Amiens SC": "amiens-sc.png",
  "Angers SCO": "angers-sco.png",
  "Atalanta Bergame": "atalanta-bergame.png",
  "Athletic Bilbao": "athletic-bilbao.png",
  "Atlético de Madrid": "atletico-de-madrid.png",
  "BSC Young Boys": "bsc-young-boys.png",
  "Bayer Leverkusen": "bayer-leverkusen.png",
  "Bayern Munich": "bayern-munich.png",
  "Bologne FC": "bologne-fc.png",
  "Borussia Dortmund": "borussia-dortmund.png",
  "Borussia Mönchengladbach": "borussia-monchengladbach.png",
  "Bourg-en-Bresse 01": "bourg-en-bresse-01.png",
  "Celta Vigo": "celta-vigo.png",
  "Clermont Foot 63": "clermont-foot-63.png",
  "Club Bruges": "club-bruges.png",
  "Dijon FCO": "dijon-fco.png",
  "EA Guingamp": "ea-guingamp.png",
  "ESTAC Troyes": "estac-troyes.png",
  "Eintracht Francfort": "eintracht-francfort.png",
  "FC Annecy": "fc-annecy.png",
  "FC Augsburg": "fc-augsburg.png",
  "FC Barcelone": "fc-barcelone.png",
  "FC Bâle": "fc-bale.png",
  "FC Cologne": "fc-cologne.png",
  "FC Fleury 91": "fc-fleury-91.png",
  "FC Lorient": "fc-lorient.png",
  "FC Lugano": "fc-lugano.png",
  "FC Metz": "fc-metz.png",
  "FC Nantes": "fc-nantes.png",
  "FC Rouen": "fc-rouen.png",
  "FC Sion": "fc-sion.png",
  "FC Sochaux-Montbéliard": "fc-sochaux-montbeliard.png",
  "FC Versailles": "fc-versailles.png",
  "FC Villefranche-Beaujolais": "fc-villefranche-beaujolais.png",
  "FC Zurich": "fc-zurich.png",
  "Fiorentina": "fiorentina.png",
  "Grenoble Foot 38": "grenoble-foot-38.png",
  "Inter Milan": "inter-milan.png",
  "Juventus": "juventus.png",
  "KRC Genk": "krc-genk.png",
  "LOSC Lille": "losc-lille.png",
  "La Gantoise": "la-gantoise.png",
  "La Roche-sur-Yon VF": "la-roche-sur-yon-vf.png",
  "Lazio Rome": "lazio-rome.png",
  "Le Havre AC": "le-havre-ac.png",
  "Le Mans FC": "le-mans-fc.png",
  "Le Puy Foot 43": "le-puy-foot-43.png",
  "Montpellier HSC": "montpellier-hsc.png",
  "OGC Nice": "ogc-nice.png",
  "Olympique Lyonnais": "olympique-lyonnais.png",
  "Olympique de Marseille": "olympique-de-marseille.png",
  "Paris 13 Atlético": "paris-13-atletico.png",
  "Paris FC": "paris-fc.png",
  "Paris Saint-Germain": "paris-saint-germain.png",
  "Pau FC": "pau-fc.png",
  "Quevilly Rouen Métropole": "quevilly-rouen-metropole.png",
  "RC Lens": "rc-lens.png",
  "RC Strasbourg": "rc-strasbourg.png",
  "RSC Anderlecht": "rsc-anderlecht.png",
  "Real Betis": "real-betis.png",
  "Real Madrid": "real-madrid.png",
  "Real Sociedad": "real-sociedad.png",
  "Red Star FC": "red-star-fc.png",
  "Rodez AF": "rodez-af.png",
  "Royal Antwerp": "royal-antwerp.png",
  "SC Aubagne Air-Bel": "sc-aubagne-air-bel.png",
  "SC Bastia": "sc-bastia.png",
  "SM Caen": "sm-caen.png",
  "SSC Naples": "ssc-naples.png",
  "Servette FC": "servette-fc.png",
  "Sporting Charleroi": "sporting-charleroi.png",
  "Stade Brestois": "stade-brestois.png",
  "Stade Lavallois": "stade-lavallois.png",
  "Stade Rennais": "stade-rennais.png",
  "Stade de Reims": "stade-de-reims.png",
  "Standard de Liège": "standard-de-liege.png",
  "Séville FC": "seville-fc.png",
  "Torino FC": "torino-fc.png",
  "Toulouse FC": "toulouse-fc.png",
  "UD Almería": "ud-almeria.png",
  "US Boulogne": "us-boulogne.png",
  "US Concarneau": "us-concarneau.png",
  "US Orléans": "us-orleans.png",
  "US Thionville Lusitanos": "us-thionville-lusitanos.png",
  "USL Dunkerque": "usl-dunkerque.png",
  "Union Saint-Gilloise": "union-saint-gilloise.png",
  "Valence CF": "valence-cf.png",
  "Valenciennes FC": "valenciennes-fc.png",
  "VfB Stuttgart": "vfb-stuttgart.png",
  "Villarreal CF": "villarreal-cf.png",
};
